import {Container} from "../../shared/ui";
import React from "react";
import {Typography} from "@/src/shared/ui/typography/typography";
import DollarLogo from '/public/header/dollar-logo.svg'
import Image from "next/image";
import VerticalDivider from '/public/header/vertical-line.svg'
import Vk from '/public/header/vk.svg'
import Viber from '/public/header/viber.svg'
import Tg from '/public/header/tg.svg'

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata: Metadata = {
//   title: 'Some title',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
          <Header />
          {children}
      </>
  )
}

const Header = () => {
  return <Container className={'relative'}>
    <div className={'absolute z-[1] w-full left-0 top-0 h-[90px]'}>
        <Container className={'h-full max-w-[1000px] mx-auto flex items-center'}>
          <div className={'flex justify-between items-center w-full'}>
            <HeaderIcon />
            <Navigation />
          </div>
        </Container>
      </div>
  </Container>
}

const HeaderIcon = () => {
  return (
      <div className={'flex items-center'}>
          <Image src={DollarLogo} alt={'$'} className={'mr-[3px]'}/>
          <Image src={VerticalDivider} alt={'|'} className={'mr-[3px]'}/>

          <div className={'flex flex-col mt-[5px]'}>
              <Typography variant={'base'} className={'leading-[0.9rem]'}>
                  Списание долгов
              </Typography>
              <Typography variant={'blue-sm'}>
                  Юрист Наталия Гулевич
              </Typography>
          </div>
      </div>
  )
}

const Navigation = () => {
  return (
      <div className={'flex justify-between min-w-[650px]'}>
        <Typography variant={'base'}>
            Главная
        </Typography>
        <Typography variant={'base'}>
             Обо мне
        </Typography>
       <Typography variant={'base'}>
              Услуги
        </Typography>
        <Typography variant={'base'}>
              Обратная связь
        </Typography>
        <SocialNetworkLinks />
      </div>
  )
}

const SocialNetworkLinks = () => {
    return (
        <div className={'relative w-[54px]'}>
            <div className={'absolute -top-[4px] -left-[20px] -translate-y-1/2'}>
                <div className={'relative h-[20px] w-[60px]'}>
                    <Image src={Vk} alt={'Вконтакте'} className={'absolute left-0 top-[1px]'}/>
                    <Image src={Tg} alt={'Телеграмм'} className={'absolute left-[17px]'}/>
                    <Image src={Viber} alt={'Вайбер'} className={'absolute left-[36px] top-[1px]'}/>
                </div>
            </div>
        </div>
    )
}