import {Container, IconButton, Modal} from "../../shared/ui";
import React, {useState} from "react";
import {Typography} from "@/src/shared/ui/typography/typography";
import LogoWhite from '/public/logo-white.svg'
import Image from "next/image";
import VerticalDivider from '/public/header/vertical-line.svg'
import Vk from '/public/header/vk.svg'
import Viber from '/public/header/viber.svg'
import Tg from '/public/header/tg.svg'
import BurgerMenuLogo from '/public/burger.png'
import Link from "next/link";
import {useScreen} from "@/src/shared/hooks";
import {Close} from "@/src/shared/assets/ui";

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })
//
// export const metadata: Metadata = {
//   title: 'Some title',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
      <>
          <Header />
          {children}
      </>
  )
}

const Header = () => {
    const screen = useScreen()
    const [isBurgerOpen, setIsBurgerOpen] = useState(false)
    return (
        <>
            {(screen === "sm" || screen === "xs") && isBurgerOpen ? (
                <BurgerMenuPopup
                    setIsOpen={setIsBurgerOpen}
                    isOpen={isBurgerOpen}
                />
            ): null}
            <Container className={'relative max-w-[1000px]'}>
                <div className={'absolute z-[1] w-full left-0 top-0 md:h-[90px] h-[60px]'}>
                    <Container className={'h-full flex items-center px-[20px]'}>
                        <div className={'flex justify-between items-center w-full'}>
                            <HeaderIcon />
                            <Navigation
                                setIsOpenBurgerPopup={setIsBurgerOpen}
                            />
                        </div>
                    </Container>
                </div>
            </Container>
        </>
        )

}

const HeaderIcon = () => {
  return (
      <Link
          href={'/'}
          className={'flex items-center min-w-[13rem]'}
      >
          {/*<Image src={LogoWhite} alt={'Ю'} className={'mr-[3px] w-[30px] h-[30px]]'}/>*/}
          {/*<Image src={VerticalDivider} alt={'|'} className={'mr-[3px]'}/>*/}

          <div className={'flex flex-col mt-[5px]'}>
              <Typography variant={'base'} className={'leading-[0.9rem]'}>
                  Сдача сессии
              </Typography>
              <Typography variant={'blue-sm'} className={'font-montserrat-light'}>
                  Базунов Андрей Сергеевич
              </Typography>
          </div>
      </Link>
  )
}

type NavigationProps = {
    setIsOpenBurgerPopup: (isOpen: boolean) => void
}

const Navigation = (props: NavigationProps) => {
  return (
      <>
          <div className={'flex md:justify-between justify-end md:w-[65%] gap-x-10'}>
              <div className={'md:hidden'}>
                  <Image
                      src={BurgerMenuLogo}
                      alt={'='}
                      priority
                      className={'cursor-pointer'}
                      onClick={() => props.setIsOpenBurgerPopup(true)}
                  />
              </div>
              <div className={'md:block hidden md:w-full'}>
                 <div className={'flex justify-between w-full'}>
                     <Typography variant={'base'} className={'font-montserrat-light'}>
                         <Link href={'/#'}>
                             Главная
                         </Link>
                     </Typography>
                     <Typography variant={'base'} className={'font-montserrat-light'}>
                         <Link href={'/#about-me'}>
                             Обо мне
                         </Link>
                     </Typography>
                     <Typography variant={'base'} className={'font-montserrat-light'}>
                         <Link href={'/#services'}>
                             Услуги
                         </Link>
                     </Typography>
                     <Typography variant={'base'} className={'font-montserrat-light'}>
                         <Link href={'/#feedback'}>
                             Обратная связь
                         </Link>
                     </Typography>
                 </div>
              </div>
              <SocialNetworkLinks />
          </div>
      </>
  )
}

const SocialNetworkLinks = () => {
    return (
        <div className={'relative w-[5rem] min-w-[5rem]'}>
            <div className={'absolute top-[-0.5rem] md:-top-[0.25rem] -left-[1.25rem] -translate-y-1/2'}>
                <div className={'relative h-[20px] w-[60px] select-none'}>
                    <Image src={Vk} alt={'Вконтакте'} className={'absolute left-0 top-[1px]'}/>
                    <Image src={Tg} alt={'Телеграмм'} className={'absolute left-[17px]'}/>
                    <Image src={Viber} alt={'Вайбер'} className={'absolute left-[36px] top-[1px]'}/>

                    {/*ссылка на вк*/}
                    <Link
                        target={'_blank'}
                        href={'https://vk.com/gulevichnatali'}
                        className={'block absolute top-[18px] left-[20px] z-10 h-[16px] w-[16px]'}
                    />

                    {/*ссылка на телеграм*/}
                    <Link
                        target={'_blank'}
                        href={'https://t.me/GulevichNatali'}
                        className={'block absolute top-[14px] left-[37px] z-10 h-[24px] w-[22px]'}
                    />

                    {/*ссылка на вайбер*/}
                    <Link
                        target={'_blank'}
                        href={'https://wa.me/+79085714448'}
                        className={'block absolute top-[17px] left-[58px] z-10 h-[18px] w-[18px]'}
                    />
                </div>
            </div>
        </div>
    )
}

type BurgerMenuPopup = {
    isOpen: boolean;
    setIsOpen: (isOpen: boolean) => void
}

const BurgerMenuPopup = (props: BurgerMenuPopup) => {
    return (
        <Modal
            isOpen={props.isOpen}
            onClose={() =>  props.setIsOpen(false)}
        >
            <div className={'bg-black bg-opacity-95 w-full h-[100vh] bg-no-repeat bg-cover'}>
                <div className={'flex justify-end p-2'}>
                    <IconButton
                        variant="outlined"
                        onClick={(e) => props.setIsOpen(false)}>
                        <Close />
                    </IconButton>
                </div>

                <div className={'flex justify-start flex-col'}>
                    <div className={'h-[45px] flex items-center justify-center border-y-[1px] border-white border-opacity-70'}>
                        <Typography className={'font-semibold'}>
                            <Link
                                href={'#'}
                                onClick={() => props.setIsOpen(false)}
                            >
                                Главная
                            </Link>
                        </Typography>
                    </div>
                    <div className={'h-[45px] flex items-center justify-center border-b-[1px] border-white border-opacity-70'}>
                        <Typography className={'font-semibold'}>
                            <Link
                                href={'#about-me'}
                                onClick={() => props.setIsOpen(false)}
                            >
                                Обо мне
                            </Link>
                        </Typography>
                    </div>
                    <div className={'h-[45px] flex items-center justify-center border-b-[1px] border-white border-opacity-70'}>
                        <Typography className={'font-semibold'}>
                            <Link
                                href={'#services'}
                                onClick={() => props.setIsOpen(false)}
                            >
                                Услуги
                            </Link>
                        </Typography>
                    </div>
                    <div className={'h-[45px] flex items-center justify-center border-b-[1px] border-white border-opacity-70'}>
                        <Typography className={'font-semibold'}>
                            <Link
                                href={'#feedback'}
                                onClick={() => props.setIsOpen(false)}
                            >
                                Обратная связь
                            </Link>
                        </Typography>
                    </div>
                </div>
            </div>
        </Modal>
    )
}